app:
  rabbitmq:
    exchange: resume.exchange
    request-routing-key: resume.request
    response-routing-key: resume.response
    request-queue: resume.request.queue
    response-queue: resume.response.queue
    sleep-timeout: 10000

spring:
  application:
    name: data-processor
  datasource:
    url: jdbc:postgresql://localhost:5430/mainDataDB
    username: usr
    password: pwd
  flyway:
    enabled: true

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: usr
    password: pwd

management:
  endpoints:
    web:
      exposure:
        include: prometheus, health
      base-path: /
      path-mapping:
        prometheus: /metrics
  endpoint:
    health:
      show-details: always
  health:
    defaults:
      enabled: true

logging:
  level:
    org.springframework.amqp: debug
    org.springframework.web: debug
    org.springframework.boot.actuate.metrics: debug
    io.micrometer: debug
  file:
    name:
      ./log/data-processor.log

resilience4j:
  circuitbreaker:
    instances:
      templateService:
        registerHealthIndicator: true
        slidingWindowSize: 20
        minimumNumberOfCalls: 6
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        failureRateThreshold: 50
        eventConsumerBufferSize: 10